# Generated by Django 4.2.2 on 2023-06-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.FilePathField(path='media/avatars/', verbose_name='аватарка'),
        ),
    ]
